Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -1,7 +1,3 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
 # This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
 
@@ -37,7 +33,7 @@ jobs:
     - name: Build with Gradle Wrapper
       run: ./gradlew build
 
-		# if exit status not equal to 0 then exit 1
+    # if exit status not equal to 0 then exit 1
     - name: Run Tests
       run: |
         ./gradlew test --info
