Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -7,27 +7,7 @@ on:
     branches: [ "main" ]
 
 jobs:
-  run-tests:
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
-    steps:
-      - uses: actions/checkout@v4
-      - name: Setup JDK
-        uses: actions/setup-java@v4
-        with:
-          java-version: '21'
-          distribution: 'temurin'
-      - name: Run tests
-        run: |
-          ./gradlew test --info
-          if [ $? -ne 0 ]; then exit 1; fi
-      - name: Fail job if tests failed
-        if: failure()
-        run: echo "Tests failed, stopping the job"
-
-  gradle-build:
-    needs: run-tests
+  gradle-test-build:
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -43,15 +23,22 @@ jobs:
       uses: gradle/actions/setup-gradle@v4
       with:
         gradle-version: current
-    - name: Make gradlew executable
+    - name: Grant execute permission for gradlew
       run: chmod +x ./gradlew
+    - name: Run tests
+      run: |
+        ./gradlew test --info
+        if [ $? -ne 0 ]; then exit 1; fi
+    - name: Fail job if tests failed
+      if: failure()
+      run: echo "Tests failed, stopping the job"
     - name: Build with Gradle Wrapper
       run: ./gradlew build
     - name: Move JAR to workspace
       run: mv build/libs/*.jar $GITHUB_WORKSPACE/built.jar
 
   upload-jar:
-    needs: gradle-build
+    needs: gradle-test-build
     runs-on: ubuntu-latest
     permissions:
       contents: write
