Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -42,9 +42,13 @@ jobs:
         ./gradlew test --info
         if [ $? -ne 0 ]; then exit 1; fi
 
+    # - name: Fail Job if Tests Failed
+    #   run: echo "Tests failed, stopping the job"
+    #        if [[ $(./gradlew test --quiet) != "BUILD SUCCESSFUL" ]]; then exit 1; fi
+
     - name: Fail Job if Tests Failed
+      if: failure()
       run: echo "Tests failed, stopping the job"
-           if [[ $(./gradlew test --quiet) != "BUILD SUCCESSFUL" ]]; then exit 1; fi
 
   dependency-submission:
 
